- lib/cogs/Music.py
Features:
- added shuffle feature #28
> Shuffle feature

- lib/bot/__init__.py
[https://github.com/MasterOfCubesAU/MOCBOT/issues/36](https://github.com/MasterOfCubesAU/MOCBOT/issues/36) - Patch
> bot no pfp bug fix

- lib/cogs/Cogs.py
Cogs.py is using hardcoded configuration issue created by FawnCobra
Fixed using config.
> Cogs.py simple patch

- lib/cogs/Levels.py
- lib/cogs/Lobbies.py
> fixed rank and lobby issue

- lib/cogs/Lobbies.py
> fixed kicking users in lobby

- lib/cogs/AFK.py
> fixed caching afk error

- lib/cogs/Music.py
- Added new jump command 
- Modified input of seek command to take in time string such as 1:10 instead of a total number of seconds 
- Changed a few 'magic numbers' for timed deletion of embeds to use pre-defined constant
> added jump and modified seek function

- lib/cogs/Music.py
- Added an autoplay feature to allow the bot to continue playing music based on the previous playing song
- Modified skip functionality to allow users to skip if there is only one song playing (it will stop and disconnect the bot)
- Modified displaying of queue modifiers on the now playing embed
> Added autoplay feature

- lib/cogs/Music.py
- requirements.txt
- utils/MusicLyrics.py
- utils/MusicQueue.py
- Added lyrics feature to music bot
- Removed extra loop function
- Modified autoplaying to support other songs not played from YouTube
> Added lyrics feature

- lib/cogs/Verification.py
Fixed an incorrect link in the verification system.
Closes #66
> Fixed broken links in verification

- lib/cogs/Verification.py
Verification prompts now have buttons rather than hyperlinks
Fixes #68 
Before:
After:
> Added buttons to verification prompts

- lib/cogs/Verification.py
> Made verification timeout kick messages more accurate

- lib/cogs/Music.py
Bug fix:
- Aims to resolve an issue with autoplay that prevents songs from playing
> Fixing autoplay issue (for the final time, hopefully!)

- config.template.yml
Update config template to reflect use of docker
> Updated config template

- config.template.yml
- lib/bot/__init__.py
- lib/cogs/AFK.py
- lib/cogs/Cogs.py
- lib/cogs/Commands.py
- lib/cogs/Levels.py
- lib/cogs/Lobbies.py
- lib/cogs/Music.py
- lib/cogs/UserModeration.py
- lib/cogs/Verification.py
- lib/socket/Socket.py
- lib/socket/namespaces/Verification.py
- utils/APIHandler/__init__.py
- utils/ConfigHandler/__init__.py
- utils/Lavalink.py
- Fixes config.template to use correct default params for Lavalink
- Removed old code pertaining to 'developers' in config
- Removed dependencies to hard coded developer IDs
- Modified cog commands to check for developers instead of guild
- Abstracted config loading to a separate static class 
- Improved the convertToInt function within APIHandler to handle list conversions as well
> Misc fixes

- lib/bot/__init__.py
> fix attribute error

- requirements.txt
> updating lavalink version

- .flake8
- .github/workflows/mocbot_ci.yml
- .pre-commit-config.yaml
- launcher.py
- lib/bot/__init__.py
- lib/cogs/AFK.py
- lib/cogs/Cogs.py
- lib/cogs/Commands.py
- lib/cogs/ErrorHandler.py
- lib/cogs/Guilds.py
- lib/cogs/Levels.py
- lib/cogs/Lobbies.py
- lib/cogs/Music.py
- lib/cogs/Roles.py
- lib/cogs/Status.py
- lib/cogs/Template.py
- lib/cogs/UserModeration.py
- lib/cogs/Verification.py
- lib/socket/Socket.py
- lib/socket/namespaces/Verification.py
- pyproject.toml
- requirements-dev.txt
- utils/APIHandler/__init__.py
- utils/ColouredFormatter.py
- utils/ConfigHandler/__init__.py
- utils/Lavalink.py
- utils/MusicFilters.py
- utils/MusicLyrics.py
- utils/MusicQueue.py
Adding linting, CI on GitHub, as well as pre-commit hook to check linting.
Black is an autoformatter which will aim to rectify as many of the lint issues as possible.
All code changes are linting fixes.
> 👷 Add linting, CI and pre-commit hook 

- .github/workflows/mocbot_ci.yml
- .pre-commit-config.yaml
- lib/cogs/Music.py
Fixing formatting issues introduced in previous PRs. This was done to maintain readability and consistency.
Additionally, this PR addresses an issue where the CI was not checking out the repository and thus was not actually running lint checks.
> 🎨 Fix formatting and CI check

- utils/MusicQueue.py
Fixed a bug in the music queue caused by a mismatched function name call.
> 🐛 Fix bug with music queue

- .dockerignore
- lavalink/application.template.yaml
Upgrading to fix Spotify playback issue.
Also removing `pyproject.toml` from `dockerignore` to ensure that the build builds locally.
> ⬆️ Upgrade lavasrc plugin to 4.6.0
